name: Continuous Deployment

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Choose Operation'
        options:
          - deploy
          - update
        type: choice

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Setup Virtual Environment
        run: |
          python -m venv noftsite
          source noftsite/bin/activate

      - name: Install Dependencies
        run: |
          source noftsite/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Setup up Requirements
        run: |
          source noftsite/bin/activate
          python load_env.py

      - name: "${{github.event.inputs.choice}}"
        run: |
          source noftsite/bin/activate
          zappa "${{github.event.inputs.choice}}" production
        
         